### ISSUE TITLE
ORDER BY bug

### ISSUE THREAD

**Issue by Viannaiv** [hy-sql/hy-sql-backend#101]
**Describe the bug**
ORDER BY ei järjestä tuloksia, jos sarake jonka mukaan pyydetään järjestämään ei ole myös pyydetyissä sarakkeissa. Eli "SELECT nimi FROM Tuotteet ORDER BY hinta;" ei toimi oikein, mutta "SELECT hinta FROM Tuotteet ORDER BY hinta;" ja "SELECT nimi, hinta FROM Tuotteet ORDER BY hinta;" toimii.

**To Reproduce**
1. https://hy-sql.netlify.app/
 2. syötä ja lähetä kysely:
      CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);
      INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);
      INSERT INTO Tuotteet (nimi, hinta) VALUES ('omena', 5);
      INSERT INTO Tuotteet (nimi, hinta) VALUES ('plop', 8);
      SELECT nimi FROM Tuotteet ORDER BY hinta;

Palauttaa: 

    nimi
    --
    retiisi
    omena
    plop

**Expected behavior**

    nimi
    --
    omena
    retiisi
    plop

**Comment by shomarov** [comment]
fixed in #102
