### ISSUE TITLE
Select parser bug

### ISSUE THREAD

**Issue by shomarov** [hy-sql/hy-sql-backend#107]
**Describe the bug**
Select parseri yhdistää haettavia sarakkeita, jos ne eivät ole erotettu pilkulla.

**To Reproduce**
1. Go to https://hy-sql.netlify.app/
2. syötä ja lähetä kysely:
CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);
INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);
INSERT INTO Tuotteet (nimi, hinta) VALUES ('omena', 5);
INSERT INTO Tuotteet (nimi, hinta) VALUES ('plop', 8);
SELECT id nimi, hinta FROM Tuotteet;

**Current behavior**
Parsii komennon muotoon:
{
      name: 'SELECT',
      fields: [
        { type: 'column', value: 'idnimi' },
        { type: 'column', value: 'hinta' }
      ],
      from: 'FROM',
      tableName: 'Tuotteet',
      finalSemicolon: ';'
}

**Expected behavior**
Palauttaa virheen

**Comment by anL1** [comment]
Onko tämä bugi vai enemmän ns. feature? Näyttäisi palauttavan tällä hetkellä virheen `no such column idnimi` eli parsii tuon välinlyönnin pois ja ei löydä vastaavaa saraketta. Olisiko jokin muu virheviesti selkeämpi? Tietysti tuon voisi columnSchemassa validoida virheeksi `column name can't contain whitespace` tms.

**Comment by shomarov** [comment]
On se bugi kun se parsii ei-toivotulla tavalla. Tämän vois ehkä ratkaista parsimisen alussa tapahtuvalla regex tarkistuksella.
