### ISSUE TITLE
Parameter given to MIN does not match any existing column

### ISSUE THREAD

**Issue by isopoju** [hy-sql/hy-sql-backend#112]
Seuraava osoitteessa [https://hy-sql.netlify.app/] tehty kysely:

CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);
INSERT INTO Tuotteet (nimi, hinta) VALUES ('nauris', 1);
INSERT INTO Tuotteet (nimi, hinta) VALUES ('bucket', 0);
SELECT AVG(hinta), COUNT(*), MAX(hinta), MIN(hinta), SUM(hinta) FROM Tuotteet;

palauttaa
Table Tuotteet created successfully
INSERT INTO Tuotteet -query was executed succesfully
INSERT INTO Tuotteet -query was executed succesfully
Parameter given to MIN does not match any existing column

Seuraava kysely toimii:
CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);
INSERT INTO Tuotteet (nimi, hinta) VALUES ('nauris', 1);
INSERT INTO Tuotteet (nimi, hinta) VALUES ('bucket', 1);
SELECT AVG(hinta), COUNT(*), MAX(hinta), MIN(hinta), SUM(hinta) FROM Tuotteet;

Virheilmoitus "Parameter given to MIN does not match any existing column" näyttäisi tulevan silloin kun halvimman tuotteen hinta=0

Vastaava virheilmoitus tulee jos kalleimman tuotteen hinta=0. Silloin virheilmoitus on "Parameter given to MAX does not match any existing column".

**Comment by Viannaiv** [comment]
Bugi johtuu siitä että 0 on falsy javascriptissä ja palutuvan vastauksen olemassa olon tarkistus on tehty if(!result). Tämä sama ongelma ilmenee myös LENGTH, AVG ja SUM funktioiden kanssa samasta syystä. Korjaan nämä samalla.
